"""sprint 3 and 4

Revision ID: 420fe8cd4298
Revises: c3a1f0e58d92
Create Date: 2026-05-06 08:40:47.403264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420fe8cd4298'
down_revision: Union[str, Sequence[str], None] = 'c3a1f0e58d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
