"""new model

Revision ID: 604e7c13abcc
Revises: c4e7a9d2f8b1
Create Date: 2026-05-18 19:33:22.558356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604e7c13abcc'
down_revision: Union[str, Sequence[str], None] = 'c4e7a9d2f8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('signed_lease_urls', sa.JSON(), nullable=True))
    op.alter_column('leases', 'rent_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('leases', 'deposit_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('leases', 'billing_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('leases', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint(op.f('leases_unit_id_fkey'), 'leases', type_='foreignkey')
    op.drop_constraint(op.f('leases_tenant_id_fkey'), 'leases', type_='foreignkey')
    op.create_foreign_key(None, 'leases', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'leases', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('leases', 'signed_lease_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('signed_lease_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.create_foreign_key(op.f('leases_tenant_id_fkey'), 'leases', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('leases_unit_id_fkey'), 'leases', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('leases', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('leases', 'billing_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('leases', 'deposit_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('leases', 'rent_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('leases', 'signed_lease_urls')
    # ### end Alembic commands ###
