"""add custom fields to leases

Revision ID: bf148883c14e
Revises: c01b66b37b2b
Create Date: 2026-05-21 17:32:32.760441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf148883c14e'
down_revision: Union[str, Sequence[str], None] = 'c01b66b37b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('custom_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'custom_fields')
    # ### end Alembic commands ###
