LANDLORD = "LANDLORD"
PROPERTY_MANAGER = "PROPERTY_MANAGER"
FINANCE = "FINANCE"
TENANT = "TENANT"
SYSTEM = "SYSTEM"

ALL_ROLES = [
    LANDLORD,
    PROPERTY_MANAGER,
    FINANCE,
    TENANT,
    SYSTEM,
]